### ISSUE TITLE
Using `disk` input plugin from inside Docker container

### ISSUE THREAD

**Issue by johnrengelman** [influxdata/telegraf-docker#11]
Trying to deploy telegraf as a monitoring agent using the Docker container onto all the hosts in my docker cluster. I'd like to use the `disk` input plugin to gather disk usage metrics, but it seems to only obtain metrics from the container's mounts instead of the host's.

This is the configuration I'm using:
```
telegraf:
  command:
    - -config
    - /config/telegraf/telegraf.conf
  image: registry.devops.connectedfleet.io/influxdata/telegraf-docker:0.12.1
  volumes_from:
    - telegraf-conf
  net: host
  environment:
    HOST_PROC: /rootfs/proc
    HOST_SYS: /rootfs/sys
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /sys:/rootfs/sys:ro
    - /proc:/rootfs/proc:ro
```

Do I also need to mount the
